BBAD-Furniture/BBAD-furniture

package-lock.json
server/db/models/products.js

Finished product model

---

package-lock.json
server/db/models/cart.js
server/db/models/index.js
server/db/models/review.js
server/db/models/user.js

User model #36

---

client/app.js
client/components/ProductList.js
client/store/index.js
client/store/productList.js

productList component and corresponding reducer created. reducer joined in combineReducer

productlist component and reducer initialized

---

client/routes.js
server/api/products.js

finished product routes

---

client/app.js
client/components/LandingPage.js
client/components/ProductList.js
client/components/SingleProduct.js
client/components/index.js
client/routes.js
client/store/index.js
client/store/productList.js
client/styles/index.css
client/styles/navbar.css
package-lock.json
public/index.html
script/seed.js
server/db/models/products.js

View all products frontend#5

---

client/components/ProductList.js
client/components/SingleProduct.js
client/components/navbar.js
client/routes.js
client/store/index.js
client/store/productList.js
client/styles/index.css
public/index.html

Single page view#5

---

.gitignore
client/store/user.js
script/seed.js
server/auth/google.js
server/auth/index.js
server/db/models/user.js
server/index.js

Authorize#40

---

client/components/Filtered.js
client/components/ProductList.js
client/components/Sidebar.js
client/components/index.js
client/routes.js
client/store/filter.js
client/store/index.js
script/seed.js

finished filter

---

server/api/products.js
server/api/users.js

refactored eager-loading for products and user

---

client/components/Cart.js
client/components/index.js
client/routes.js
server/api/products.js

cart function but not complete. needs to refactor with singleProduct component.

sudo cart finished

---

client/components/Cart.js
client/store/cart.js

we're back on track, I think. items are stored on local storage, persists after refresh and closed tab.

Persist cart items with local storage complete

---

client/components/auth-form.js
client/components/navbar.js
client/components/user-home.js
client/store/user.js
package-lock.json
server/api/users.js
server/auth/google.js
server/auth/index.js
server/db/models/user.js

Authenticated product access

---

client/components/user-home.spec.js
client/store/user.spec.js
package-lock.json
package.json
script/seed.spec.js
server/api/users.spec.js
server/db/models/orders.spec.js
server/db/models/products.spec.js
server/db/models/review.spec.js
server/db/models/user.spec.js

completed all the model testing (no association testing incase we change them again)

Model tests

---

client/components/ProductList.js
client/components/Sidebar.js
client/components/SingleProduct.js
client/components/navbar.js
client/store/filter.js
client/store/index.js
client/store/productList.js
client/styles/cart.css
client/styles/index.css
client/styles/navbar.css
client/styles/productList.css
client/styles/sidebar.css
client/styles/singleProduct.css

Search category feature

---

client/components/ProductList.js
client/components/SingleProduct.js
client/routes.js
client/store/currentProduct.js

admin can now delete a product

Admin edit delete

---

client/components/Cart.js
client/components/Checkout.js
client/components/ProductList.js
client/components/SingleProduct.js
client/components/navbar.js
client/components/user-home.js
client/store/index.js
client/store/signedInCart.js
server/api/users.js
server/db/models/orderDetail.js
server/db/models/orders.js
server/db/models/products.js
server/db/models/user.js

Login shopping

---

client/components/AddProduct.js
client/components/ProductList.js
client/components/auth-form.js
client/components/index.js
client/components/navbar.js
client/components/user-home.js
client/routes.js
client/store/productList.js
client/styles/addProductForm.css

Admin add product

---

client/components/Cart.js
client/components/Checkout.js
client/components/DoneCheckout.js
client/components/SingleProduct.js
client/components/index.js
client/routes.js
client/store/cart.js
client/styles/cart.css
client/styles/checkout.css

Checkout info

---

client/components/ProductList.js
client/components/navbar.js

Reverts BBAD-Furniture/BBAD-furniture#84

Revert "Search category feature"

---

client/components/navbar.js

fixed bug for search

---

client/components/EditProduct.js
client/components/ProductList.js
client/components/SingleProduct.js
client/components/index.js
client/store/currentProduct.js

Admin edit product

---

client/components/AddProduct.js
client/components/ProductList.js
client/store/productList.js

fixed search bug error

---

client/components/Cart.js
client/components/Checkout.js
client/components/SingleProduct.js
client/styles/checkout.css

Complete checkout exp

---

client/components/AddProduct.js
client/components/Cart.js
client/components/Checkout.js
client/components/EditProduct.js
client/components/ProductList.js
client/components/SingleProduct.js
client/components/index.js
client/routes.js
client/styles/checkout.css
server/api/products.js

Edit product

---

client/store/currentProduct.js

fixed delete item bug

---

client/components/ProductList.js
client/store/currentProduct.js
client/store/productList.js
script/seed.js
server/db/models/products.js

fixed add product bug

---

client/components/AddProduct.js
client/components/ProductList.js
client/components/SingleProduct.js
client/styles/productList.css
client/styles/singleProduct.css
script/seed.js

added stars to reviews, cleaned up seed file

---

client/components/OrderInfo.js
client/components/user-home.js

Order details

---

client/components/AddProduct.js
client/components/AddReview.js
client/components/EditProduct.js
client/components/OrderInfo.js
client/components/ProductList.js
client/components/SingleProduct.js
client/components/index.js
client/store/currentProduct.js
server/api/products.js
server/db/models/products.js

User add reviews

---

client/components/navbar.js
client/components/user-home.js
client/store/currentProduct.js
client/styles/navbar.css
client/styles/userpage.css
server/auth/index.js

Userpage and cleanup

---

client/components/OrderInfo.js
client/components/auth-form.js
client/components/user-home.js
client/routes.js
server/api/products.js
server/api/users.js

Secure route

---

client/components/SingleProduct.js
client/store/allUsers.js
client/store/currentProduct.js
server/api/products.js
server/db/models/review.js

Userpage style

---

client/components/Cart.js
client/components/navbar.js
client/store/cart.js
client/store/signedInCart.js

cart works!, separately

---

client/components/user-home.js
client/styles/userpage.css

finished user page styling

---

client/components/AddReview.js
client/components/SingleProduct.js
client/styles/addReview.css

styled add review

---

client/app.js
client/components/AddProduct.js
client/components/AddReview.js
client/components/AllUsers.js
client/components/Cart.js
client/components/EditProduct.js
client/components/OrderInfo.js
client/components/ProductList.js
client/components/SingleProduct.js
client/components/index.js
client/components/notify.js
client/components/user-home.js
client/routes.js
client/store/allUsers.js
client/store/cart.js
client/store/currentProduct.js
client/store/productList.js
client/store/signedInCart.js
client/store/user.js
client/styles/addReview.css
client/styles/cart.css
client/styles/index.css
client/styles/singleProduct.css
package-lock.json
package.json
server/api/users.js
server/db/models/products.js
server/db/models/user.js

Finish styling

---

client/components/Cart.js
client/components/Checkout.js
client/components/DoneCheckout.js
client/components/LandingPage.js
client/components/SingleProduct.js
client/components/auth-form.js
client/components/user-home.js
client/styles/cart.css
client/styles/checkout.css
client/styles/landingpage.css
client/styles/singleProduct.css
client/styles/userpage.css

Landingpage

---

client/components/Cart.js
client/components/user-home.js
client/store/signedInCart.js
package-lock.json

no comments or logs
